apiVersion: v1
kind: Deployment 
metadata:
  name: myjavaapp-deployment
  labels:
     app: myjavaapp
spec: 
  replicas: 3
  selector:
    matchlables:
          app: myjavaapp
    template:
    metadata: 
      lables: 
         app: myjavaapp
    spec:
      containers:
      - name: myjavaapp-deployment
        image: nginx
        ports:
        containerPort: 8080

      