apiVersion: v1
kind: ReplicationController
metadata:
    name: myjavaapp-rc
spec: 
  replicas: 3
  selector:
      app: myjavaapp
      version: 2.6.2
  template:
      metadata: 
      lables:
         app: myjavaapp
         version: 2.6.2
      spec:
      containers:
      - name: myjavaap-container
      image:  maha4iac/mymahalogin02april22:2
      ports:
      - containerPort: 8080
        