apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-app
spec: 
  replicas: 3
  selector:
      app: mynginx-app
      version: 2.6.2
  template:
      metadata: 
       lables:
         app: mynginx-app
         version: 2.6.2
      spec:
        containers:
        - name: mynginx-app
          image: nginx
          ports:
          - containerPort: 80
        