apiVersion: v1
kind: Service
metadata: 
    name: myjavaapp-svc
    lables:
       app: myjavaapp
       version: 2.6.2
spec:
  type: NodePotrt
  ports:
  - port: 8080
    nodeport: 30001
    protocal: TCP
  selector:
      app: myjavaapp
      version: 2.6.2
    

